name: telegram message
on:
  workflow_dispatch:
  schedule:
  - cron: '30 10 * * *'
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get countdown
        run: |
          python -m pip install --upgrade pip
          pip install fire
          echo "countdown_days=$(python bots/countdown.py)" >> $GITHUB_ENV
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ env.countdown_days }}
